version: 2.1
jobs:
  preview_deployment:
    docker:
      - image: circleci/node:latest
    environment:
      VERCEL_TOKEN: b3DAlk5Zr4ACGydtLTfzKnWs
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=b3DAlk5Zr4ACGydtLTfzKnWs
      - run:
          name: Build Project Artifacts
          command: vercel build --token=b3DAlk5Zr4ACGydtLTfzKnWs
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --token=b3DAlk5Zr4ACGydtLTfzKnWs

  production_deployment:
    docker:
      - image: circleci/node:latest
    environment:
      VERCEL_TOKEN: b3DAlk5Zr4ACGydtLTfzKnWs
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command:  npm install -g vercel 
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=production --token=b3DAlk5Zr4ACGydtLTfzKnWs
      - run:
          name: Build Project Artifacts
          command: vercel build --prod --token=b3DAlk5Zr4ACGydtLTfzKnWs
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --prod --token=b3DAlk5Zr4ACGydtLTfzKnWs

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - production_deployment:
          filters:
            branches:
              only: /main/